spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
#          issuer-uri: "http://127.0.0.1:9000/api/v1"
#          issuer-uri: "http://localhost:9000"
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: 123456
            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/api/v1/authorized"
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"
#            issuer-uri: "http://127.0.0.1:9000/api/v1"
#            issuer-uri: "http://localhost:9000"

app:
  test: in dev